### PR TITLE
jpa improvements

### PR DESCRIPTION
**Pull request by cameronbraid**
Change all enum fields on entities to be @Enumerated(EnumType.STRING) 
add @Lob to Incident.errorMessage

### CODE REVIEW

**Review by saig0 — CHANGES_REQUESTED** [review]
Thanks @cameronbraid. Looks good :cookie: 

Looking at the entities, I found two other fields that should have a `@Lob` annotation:
* `Variable`: `value`
* `VariableUpdate`: `value`

Can you please add these annotations to this PR?

**Comment by cameronbraid** [comment]
@saig0 done

**Review by saig0 — APPROVED** [review]
Thank you for your contribution @cameronbraid :cake:

**Comment by strawhat5** [comment]
Hey I just came across this same issue and was going to raise a PR for it. 😅 Glad to see this already merged. 🙂 

@saig0 Could you please release this one as well on docker?

**Comment by saig0** [comment]
Yes, I'll schedule a release :rocket:

**Comment by saig0** [comment]
Done: https://github.com/zeebe-io/zeeqs/releases/tag/1.0.0-alpha5 :balloon:

**Pull request merged**
